services:
  - type: web
    name: highrise-backend
    runtime: node
    buildCommand: cd backend && npm install && node seed.js
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
